[package]
name = "th06_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
sha256 = "1.5.0"
encoding_rs = "0.8.34"
codepage = "0.1.1"
